import { Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
type Point = Record<string, string | number>;
export default function DashboardCharts({ timeseries, statuses, types, anomalies }: { timeseries: Point[]; statuses: Point[]; types: Point[]; anomalies: Point[] }) {
  return <div className="am-chart-grid">
    <article className="officer-page-card"><h2>Hồ sơ theo thời gian</h2><div className="officer-chart"><ResponsiveContainer><LineChart data={timeseries}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="date"/><YAxis allowDecimals={false}/><Tooltip/><Line dataKey="total" stroke="#2563eb" strokeWidth={2}/><Line dataKey="completed" stroke="#109b81" strokeWidth={2}/></LineChart></ResponsiveContainer></div><p className="sr-only">Xu hướng tổng số hồ sơ và hồ sơ hoàn thành theo thời gian.</p></article>
    <article className="officer-page-card"><h2>Phân bố trạng thái</h2><div className="officer-chart"><ResponsiveContainer><PieChart><Pie data={statuses} dataKey="value" nameKey="name" innerRadius={55} outerRadius={90}>{statuses.map((item, index) => <Cell key={String(item.key ?? item.name)} fill={['#2563eb','#109b81','#f59e0b','#ef4444','#8b5cf6'][index % 5]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div><ul className="am-chart-summary">{statuses.map((item, index) => <li key={String(item.key ?? `${item.name}-${index}`)}><span className="am-chart-swatch" style={{ backgroundColor: ['#2563eb','#109b81','#f59e0b','#ef4444','#8b5cf6'][index % 5] }} aria-hidden="true" />{item.name}: <strong>{item.value}</strong></li>)}</ul></article>
    <article className="officer-page-card"><h2>Loại thủ tục</h2><div className="officer-chart"><ResponsiveContainer><BarChart data={types} layout="vertical"><CartesianGrid strokeDasharray="3 3"/><XAxis type="number" allowDecimals={false}/><YAxis type="category" dataKey="name" width={110}/><Tooltip/><Bar dataKey="value" fill="#2563eb" radius={[0,6,6,0]}/></BarChart></ResponsiveContainer></div></article>
    <article className="officer-page-card"><h2>Cảnh báo phổ biến</h2><div className="officer-chart"><ResponsiveContainer><BarChart data={anomalies} layout="vertical"><XAxis type="number" allowDecimals={false}/><YAxis type="category" dataKey="name" width={110}/><Tooltip/><Bar dataKey="value" fill="#f59e0b" radius={[0,6,6,0]}/></BarChart></ResponsiveContainer></div></article>
  </div>;
}
