import { Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
type Point = Record<string, string | number>;
const chartColors = ['var(--chart-blue)', 'var(--chart-green)', 'var(--chart-gold)', 'var(--chart-red)', 'var(--chart-violet)'];
const axisColor = 'var(--color-text-muted)';
const gridColor = 'var(--color-border)';
export default function DashboardCharts({ timeseries, statuses, types, anomalies }: { timeseries: Point[]; statuses: Point[]; types: Point[]; anomalies: Point[] }) {
  return <div className="am-chart-grid">
    <article className="officer-page-card"><h2>Hồ sơ theo thời gian</h2><div className="officer-chart" aria-hidden="true"><ResponsiveContainer><LineChart data={timeseries}><CartesianGrid stroke={gridColor} strokeDasharray="3 3"/><XAxis dataKey="date" stroke={axisColor}/><YAxis allowDecimals={false} stroke={axisColor}/><Tooltip/><Line dataKey="total" name="Tổng hồ sơ" stroke={chartColors[0]} strokeWidth={2}/><Line dataKey="completed" name="Đã hoàn thành" stroke={chartColors[1]} strokeWidth={2}/></LineChart></ResponsiveContainer></div><p className="sr-only">Xu hướng tổng số hồ sơ và hồ sơ hoàn thành theo thời gian.</p></article>
    <article className="officer-page-card"><h2>Phân bố trạng thái</h2><div className="officer-chart" aria-hidden="true"><ResponsiveContainer><PieChart><Pie data={statuses} dataKey="value" nameKey="name" innerRadius={55} outerRadius={90}>{statuses.map((item, index) => <Cell key={String(item.key ?? item.name)} fill={chartColors[index % chartColors.length]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div><ul className="am-chart-summary" aria-label="Tóm tắt phân bố trạng thái">{statuses.map((item, index) => <li key={String(item.key ?? `${item.name}-${index}`)}><span className="am-chart-swatch" style={{ backgroundColor: chartColors[index % chartColors.length] }} aria-hidden="true" /><span>{item.name}</span><strong>{item.value}</strong></li>)}</ul></article>
    <article className="officer-page-card"><h2>Loại thủ tục</h2><div className="officer-chart" aria-hidden="true"><ResponsiveContainer><BarChart data={types} layout="vertical"><CartesianGrid stroke={gridColor} strokeDasharray="3 3"/><XAxis type="number" allowDecimals={false} stroke={axisColor}/><YAxis type="category" dataKey="name" width={110} stroke={axisColor}/><Tooltip/><Bar dataKey="value" name="Hồ sơ" fill={chartColors[0]} radius={[0,6,6,0]}/></BarChart></ResponsiveContainer></div><p className="sr-only">Biểu đồ số lượng hồ sơ theo từng loại thủ tục.</p></article>
    <article className="officer-page-card"><h2>Cảnh báo phổ biến</h2><div className="officer-chart" aria-hidden="true"><ResponsiveContainer><BarChart data={anomalies} layout="vertical"><XAxis type="number" allowDecimals={false} stroke={axisColor}/><YAxis type="category" dataKey="name" width={110} stroke={axisColor}/><Tooltip/><Bar dataKey="value" name="Cảnh báo" fill={chartColors[2]} radius={[0,6,6,0]}/></BarChart></ResponsiveContainer></div><p className="sr-only">Biểu đồ các nhóm cảnh báo xuất hiện nhiều nhất.</p></article>
  </div>;
}
