"""Pydantic contracts — single source of truth giữa 3 workstream.

Đổi bất kỳ model nào ở đây = đổi contract → PR phải tag cả team (TEAM_PLAN §4).
"""

from src.models.cases import Case, CaseCreate, CaseStatus, CaseUpdate, ChecklistItem
from src.models.chat import (
    ChatAction,
    ChatCacheInfo,
    ChatRequest,
    ChatResponse,
    ChatStarterResponse,
    ChatTemplateResource,
    Citation,
    EvidenceStep,
    IntentName,
    TemplateCitation,
)
from src.models.documents import ExtractedDocument, ExtractedField
from src.models.drafts import (
    DraftDocxStyle,
    DraftFieldSpec,
    DraftGenerateRequest,
    DraftHtmlExportRequest,
    DraftLayoutBlock,
    DraftLegalSource,
    DraftRevision,
    DraftReviseRequest,
    DraftTemplate,
    DraftTemplateInfo,
    GeneratedDraft,
)
from src.models.ops import (
    AnomalyAlert,
    Assignment,
    CaseSummary,
    DailyDigest,
    MetricPoint,
)
from src.models.procedures import (
    ClarifyingQuestion,
    DocumentRequirement,
    FormField,
    FormTemplate,
    Procedure,
    ProcedureCapabilities,
    ProcedureFormSchema,
    ProcedureSummary,
)
from src.models.sources import (
    NormalizedProcedureMetadata,
    ProcedureDocument,
    ProcedureSection,
    ProvenancedValue,
    QualityReport,
    SyncResult,
)
from src.models.validation import ValidationIssue, ValidationReport
from src.models.citizen import (
    CitizenCaseCreate,
    CitizenCaseUpdate,
    CitizenSubmitRequest,
    ConsentRecord,
    RoutingDecision,
    UploadCompleteRequest,
    UploadIntentRequest,
    UploadIntentResponse,
)
from src.models.officer import (
    ApplicationCase,
    CaseAuditEvent,
    CaseDocument,
    CaseSubmissionVersion,
    ExtractedFieldRecord,
    OfficerDecision,
    OfficerIdentity,
    SupplementRequest,
    TokenClaims,
    ValidationFinding,
)

__all__ = [
    "AnomalyAlert",
    "Assignment",
    "Case",
    "CaseCreate",
    "CaseStatus",
    "CaseSummary",
    "CaseUpdate",
    "ChatRequest",
    "ChatResponse",
    "ChatAction",
    "ChatCacheInfo",
    "ChatStarterResponse",
    "ChatTemplateResource",
    "ChecklistItem",
    "ClarifyingQuestion",
    "Citation",
    "EvidenceStep",
    "DailyDigest",
    "DocumentRequirement",
    "DraftDocxStyle",
    "DraftFieldSpec",
    "DraftGenerateRequest",
    "DraftHtmlExportRequest",
    "DraftLayoutBlock",
    "DraftLegalSource",
    "DraftRevision",
    "DraftReviseRequest",
    "DraftTemplate",
    "DraftTemplateInfo",
    "ExtractedDocument",
    "ExtractedField",
    "FormField",
    "FormTemplate",
    "GeneratedDraft",
    "IntentName",
    "MetricPoint",
    "Procedure",
    "TemplateCitation",
    "ProcedureCapabilities",
    "ProcedureDocument",
    "ProcedureFormSchema",
    "ProcedureSection",
    "ProcedureSummary",
    "ProvenancedValue",
    "NormalizedProcedureMetadata",
    "QualityReport",
    "SyncResult",
    "ValidationIssue",
    "ValidationReport",
    "ApplicationCase",
    "CaseAuditEvent",
    "CaseDocument",
    "CaseSubmissionVersion",
    "ExtractedFieldRecord",
    "OfficerDecision",
    "OfficerIdentity",
    "SupplementRequest",
    "TokenClaims",
    "ValidationFinding",
    "CitizenCaseCreate",
    "CitizenCaseUpdate",
    "CitizenSubmitRequest",
    "ConsentRecord",
    "RoutingDecision",
    "UploadCompleteRequest",
    "UploadIntentRequest",
    "UploadIntentResponse",
]
